FROM reg-online.yhroot.com/satop/miniconda:healthy-management-useryinhe
## 项目根目录
ARG appname=$appname
ARG dpenv=$dpenv
ARG apphome=/yinhe/apps/$appname
ARG applog=/yinhe/logs/$appname
ARG ENV=$ENV
USER root
WORKDIR $apphome
COPY . .
COPY apps_config /yinhe/apps/config/$appname/
RUN  mkdir -p $applog && chown -R yinhe:yinhe /yinhe  && chown -R yinhe:yinhe /yinhe/apps/config/$appname/ && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
USER yinhe
ENV TZ='Asia/Shanghai'
EXPOSE 7878
ENTRYPOINT ["/opt/conda/envs/healthy-management/bin/python","start.py"]
